apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deploy-hpa
  namespace: example-app
spec:
  maxReplicas: 10 
  minReplicas: 2 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment 
    name: example-deploy
  targetCPUUtilizationPercentage: 50