apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: deploy-vpa
  namespace: example-app
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       example-deploy
  updatePolicy:
    updateMode: "Auto"